name: Backend Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '21'     # Die gewünschte Java-Version auswählen

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test